### ISSUE TITLE
KeyError: 'https' on connect.py

### ISSUE THREAD

**Issue by BillmanH** [Azure-Samples/azure-cosmos-db-graph-python-getting-started#20]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting

- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
* Clone repo
* Adjust config. This is the config.py file that I set up. 
```python
client = client.Client('https://localhost:8901/', 'g',
                        username="/dbs/db1/colls/coll1",
                        password="<copy/pasted from the explorer>",
                        message_serializer=serializer.GraphSONSerializersV2d0()
                        )
```

### Any log messages given by the failure
> `KeyError: 'https'`

### Expected/desired behavior
> not error, script runs to completion.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
W10

### Versions
```
gremlinpython==3.4.10
futures
```

### Mention any other details that might be useful
I have a local CDB graph instance that is configured properly. This connection should work (confirmed working with **tinkerpop**). I can also access and query the server from `https://localhost:8081/_explorer/index.html`

Here is the full stack trace:
```
Welcome to Azure Cosmos DB + Gremlin on Python!
We're about to drop whatever graph is on the server. Press any key to continue...

> g.V().drop()
Traceback (most recent call last):
  File "C:\Users\<user>\anaconda3\envs\npd\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\<user>\anaconda3\envs\npd\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\<user>\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\<user>\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\<user>\.vscode\extensions\ms-python.python-2021.1.502429796\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\<user>\anaconda3\envs\npd\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\<user>\anaconda3\envs\npd\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\<user>\anaconda3\envs\npd\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\<user>\source\repos\azure-cosmos-db-graph-python-getting-started\connect.py", line 181, in <module>
    cleanup_graph(client)
  File "c:\Users\<user>\source\repos\azure-cosmos-db-graph-python-getting-started\connect.py", line 58, in cleanup_graph
    callback = client.submitAsync(_gremlin_cleanup_graph)
  File "C:\Users\<user>\AppData\Roaming\Python\Python36\site-packages\gremlin_python\driver\client.py", line 148, in submitAsync
    return conn.write(message)
  File "C:\Users\<user>\AppData\Roaming\Python\Python36\site-packages\gremlin_python\driver\connection.py", line 55, in write
    self.connect()
  File "C:\Users\<user>\AppData\Roaming\Python\Python36\site-packages\gremlin_python\driver\connection.py", line 45, in connect
    self._transport.connect(self._url, self._headers)
  File "C:\Users\<user>\AppData\Roaming\Python\Python36\site-packages\gremlin_python\driver\tornado\transport.py", line 41, in connect
    lambda: websocket.websocket_connect(url, compression_options=self._compression_options))
  File "C:\Users\<user>\anaconda3\envs\npd\lib\site-packages\tornado\ioloop.py", line 576, in run_sync
    return future_cell[0].result()
  File "C:\Users\<user>\anaconda3\envs\npd\lib\site-packages\tornado\ioloop.py", line 547, in run
    result = func()
  File "C:\Users\<user>\AppData\Roaming\Python\Python36\site-packages\gremlin_python\driver\tornado\transport.py", line 41, in <lambda>
    lambda: websocket.websocket_connect(url, compression_options=self._compression_options))
  File "C:\Users\<user>\anaconda3\envs\npd\lib\site-packages\tornado\websocket.py", line 1339, in websocket_connect
    subprotocols=subprotocols)
  File "C:\Users\<user>\anaconda3\envs\npd\lib\site-packages\tornado\websocket.py", line 1123, in __init__
    scheme = {'ws': 'http', 'wss': 'https'}[scheme]
KeyError: 'https'
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by BillmanH** [comment]
I think that I may have figured this out. The schema dict provided in the error maps to what you need to replace the ulr with. 

So if your url is https then you need to change the string to `wss` and `ws` for http. 

I would delete this except that I think that it might be useful for future developers.
