### ISSUE TITLE
Error when running connect.py: "SASL information provided by client does not match expected format"

### ISSUE THREAD

**Issue by s-lopez** [Azure-Samples/azure-cosmos-db-graph-python-getting-started#29]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow the steps in the README - The error appears in `python connect.py`

### Any log messages given by the failure
> Welcome to Azure Cosmos DB + Gremlin on Python!
We're about to drop whatever graph is on the server. Press any key to continue...

> g.V().drop()
Code: 499, Attributes: {'x-ms-activity-id': '6d185eea-070e-43d1-96f4-8ee35ba42757'}
Traceback (most recent call last):
  File "connect.py", line 168, in <module>
    cleanup_graph(client)
  File "connect.py", line 64, in cleanup_graph
    callback.result().all().result() 
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/slopez/python/azure-cosmos-db-graph-python-getting-started/venv/lib/python3.8/site-packages/gremlin_python/driver/resultset.py", line 90, in cb
    f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/slopez/python/azure-cosmos-db-graph-python-getting-started/venv/lib/python3.8/site-packages/gremlin_python/driver/connection.py", line 83, in _receive
    status_code = self._protocol.data_received(data, self._results)
  File "/Users/slopez/python/azure-cosmos-db-graph-python-getting-started/venv/lib/python3.8/site-packages/gremlin_python/driver/protocol.py", line 99, in data_received
    return self.data_received(data, results_dict)
  File "/Users/slopez/python/azure-cosmos-db-graph-python-getting-started/venv/lib/python3.8/site-packages/gremlin_python/driver/protocol.py", line 112, in data_received
    raise GremlinServerError(message["status"])
**gremlin_python.driver.protocol.GremlinServerError: 499: ActivityId: 6d185eea-070e-43d1-96f4-8ee35ba42757
SASL information provided by client does not match expected format.**

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "connect.py", line 210, in <module>
    cosmos_status_code = e.status_attributes["x-ms-status-code"]
KeyError: 'x-ms-status-code'

### Expected/desired behavior
> The script runs without errors.

### OS and Version?
> macOS Monterey 12.4

### Versions
> python: 3.8.2
```
pip list

Package       Version
------------- -----------
aenum         2.2.6
certifi       2022.5.18.1
futures       3.0.5
gremlinpython 3.4.13
isodate       0.6.1
pip           22.1.2
setuptools    60.2.0
six           1.16.0
tornado       5.1.1
wheel         0.37.1
```

### Mention any other details that might be useful
First time trying to run the script. Googling didn't help to find a solution, unfortunately. Thanks for taking a look at this!

**Comment by olivertowers** [comment]
`SASL information provided by client does not match expected format` indicates that the user-name or password were not valid values.

Per the [getting started docs](https://docs.microsoft.com/en-us/azure/cosmos-db/graph/create-graph-python#update-your-connection-information), the username/password parameters for `Client` constructor will need to be updated.

```python
username="/dbs/<DATABASE_NAME>/colls/<CONTAINER_NAME>", 
password="<ACCOUNT_PRIMARY_AUTH_KEY>"
```

If you have updated this and are still facing issues, please share the username value.

**Comment by s-lopez** [comment]
That is correct. Despite double-checking, there was still a typo in the password. Thanks for the heads-up!
