### ISSUE TITLE
Difficulty in running the sample, connect.py results in error while retrieving vertex insertion result

### ISSUE THREAD

**Issue by kuldeepyadav** [Azure-Samples/azure-cosmos-db-graph-python-getting-started#7]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run connect.py 

### Any log messages given by the failure
> There was an exception: 'NoneType' object has no attribute 'decode'
Traceback (most recent call last):
  File "connect.py", line 132, in <module>
    insert_vertices(client)
  File "connect.py", line 58, in insert_vertices
    print("\tInserted this vertex:\n\t{0}\n".format(callback.result().one()))
  File "/datadrive/stackoverflow/lib/python3.4/site-packages/gremlin_python/driver/resultset.py", line 74, in one
    return self.done.result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/datadrive/stackoverflow/lib/python3.4/site-packages/gremlin_python/driver/connection.py", line 77, in _receive
    self._protocol.data_received(data, self._results)
  File "/datadrive/stackoverflow/lib/python3.4/site-packages/gremlin_python/driver/protocol.py", line 69, in data_received
    data = json.loads(data.decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'

### Expected/desired behavior
> It should print vertex insertion status 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Ubuntu Linux, python version 3.4.3 

### Versions
>

### Mention any other details that might be useful

It is very strange that sometime the sample run successfully and most of time it faces the issues as described above.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by LuisBosquez** [comment]
Hello @kuldeepyadav,

Two questions, what version of gremlinpython are you using? We have rolled back to 3.2.7 given some issues that we were experiencing with the latest version. Also can you share what queries you're executing?

Thanks,
Luis

**Comment by Harshvardhan28** [comment]
Hi,

I'm also facing the same problem.
**There was an exception: 'NoneType' object has no attribute 'decode'**

Germilin = gremlinpython-3.3.3
Python Version = python-3.5.2-0
Ubuntu Linux

FYI - Adding message_serializer=serializer.GraphSONSerializersV2d0() doesn't worked for me.

The code is showing intermittent behaviour sometimes it works but most of the time it gets fails with above exception.

Thanks,
Harshvardhan

**Comment by shreenilesh** [comment]
Hi,

I have created new graph today but still facing similar error as follows while running the sample python code on github:

_"There was an exception: module 'gremlin_python.driver.serializer' has no attribute 'GraphSONSerializersV2d0'
Traceback (most recent call last):
  File "connect.py", line 107, in <module>
    message_serializer=serializer.GraphSONSerializersV2d0()
AttributeError: module 'gremlin_python.driver.serializer' has no attribute 'GraphSONSerializersV2d0'"_

Versions->
gremlinpython==3.2.7
Python : 3.7.1

Please advise.

**Comment by justinhauer** [comment]
this is still broken: 

This example in it's current form doesn't run. It could be due to the current version of gremlinpython you have the pip requirement pegged to (3.2.7). Also, when you go to run connect.py, serializer.GraphSONSerializersV2d0() isn't present in 3.2.7, only serializer.GraphSONMessageSerializer() is if you check the site packages installed. With this fix though ^, the code still doesn't run once the insert_vertices function is run, it returns:
`AttributeError: 'NoneType' object has no attribute 'decode'`

Python virtual environment: 3.7.2
Please resolve issues in example.

**Comment by VimalShekar** [comment]
still broken in :
Python 3.7.3
gremlinpython 3.2.7

>python connect.py
There was an exception: module 'gremlin_python.driver.serializer' has no attribute 'GraphSONSerializersV2d0'
Traceback (most recent call last):
  File "connect.py", line 107, in <module>
    message_serializer=serializer.GraphSONSerializersV2d0()
AttributeError: module 'gremlin_python.driver.serializer' has no attribute 'GraphSONSerializersV2d0'

**Comment by nopslip** [comment]
I upgrade to gremlinpython  3.4.6 and the issue was resolved. 

`pip install --upgrade gremlinpython`

**Comment by nopslip** [comment]
I upgrade to gremlinpython 3.4.6 and the issue was resolved. 

`pip install --upgrade gremlinpython`

**Comment by olivertowers** [comment]
Sample updated to avoid this error:
1.  Upgrading gremlin-python version to 3.4.13 (as of this comment, but the latest supported version will be updated in the sample)
2.  Specifying ` message_serializer=serializer.GraphSONSerializersV2d0()` when constructing the client.
